# fly.toml app configuration file generated for attos-earn-api-bitter-flower-6326 on 2025-03-29T22:02:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'attos-earn-api'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
