# fly.toml app configuration file generated for attos-earn-api-bitter-flower-6326 on 2025-03-29T22:02:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'attos-earn-api'
primary_region = 'ams'

[build]

[services.concurrency]
  type = "requests"
  hard_limit = 20
  soft_limit = 10

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[[http_service.checks]]
  grace_period = "5s"
  interval = "2s"
  method = "GET"
  timeout = "15s"
  path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "cache_data"
  destination = "/cache"
  initial_size = "1gb"

[env]
CACHE_DIR = "/cache"
